MVC Turnero/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

namespace MVC_Turnero.Controllers
{
    public class ConfigController : Controller
    {
        // GET: Confi
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GetConfigConsultorioJsonResult(string sistema, int? csId)
        {

            SqlConnection cx = null;

            string consulta = "";

            if (sistema.ToLower() == "mho")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_MHO"].ConnectionString);
                consulta = "select ctc.id,ctc.consultorio as ConsultorioNombre, ctc.numero as identificador, ctc.activo as Activo, (p.Apellido + ', ' + p.Nombre) as Profesional, p.ProfesionalID  from catTurneroConsultorio ctc " +
                           " inner join catTurnero ct on ct.csId = ctc.id_catTurnero " +
                           " left join Profesional p on p.ProfesionalID = ctc.PerConId " +
                           " where ct.csId = @column ";
            }
            else if (sistema.ToLower() == "gedoc")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_GEDOC"].ConnectionString);
                consulta = "select ctc.id,ctc.consultorio as ConsultorioNombre, ctc.numero as identificador, ctc.activo as Activo, x.perApellidoyNombre as Profesional, x.perId  as ProfesionalID " +
                            " from catTurneroConsultorio ctc " +
                            " inner join catTurnero ct on ct.csId = ctc.id_catTurnero " +
                            " left join  (select p.perId, p.perApellidoyNombre from catPersona p inner join catProfesion prof on prof.profId = p.profId union " +
                            " select c.conId, c.conApellidoyNombre from catPersonaContratados c inner join catProfesion prof on prof.profId = c.profId where conMotivoBaja is not null and conMotivoBaja is not null and c.conDNI not in (select perDNI from catPersona)) as x on x.perId = ctc.PerConId " +
                            " where ct.csId = @column ";
            }

            SqlDataAdapter da = new SqlDataAdapter(consulta, cx);
            da.SelectCommand.Parameters.AddWithValue("@column", csId);

            DataTable dt = new DataTable();

            try
            {
                da.Fill(dt);
            }
            catch(Exception err)
            {
                return Json(err.Message);
            }
            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> row;
            foreach (DataRow dr in dt.Rows)
            {
                row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            return Json(rows);
        }

        public JsonResult GetConfigConsultorioJsonResultId(string sistema, int? csId, string identificador)
        {

            SqlConnection cx = null;
            string consulta = "";

            if (sistema.ToLower() == "mho")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_MHO"].ConnectionString);
                consulta = "select ctc.id,ctc.consultorio as ConsultorioNombre, ctc.numero as identificador, ctc.activo as Activo, (p.Apellido + ', ' + p.Nombre) as Profesional, p.ProfesionalID  from catTurneroConsultorio ctc " +
                           " inner join catTurnero ct on ct.csId = ctc.id_catTurnero " +
                           " left join Profesional p on p.ProfesionalID = ctc.PerConId " +
                           " where ct.csId = @column and ctc.numero = @column2 ";
            }
            else if (sistema.ToLower() == "gedoc")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_GEDOC"].ConnectionString);

                consulta = "select ctc.id,ctc.consultorio as ConsultorioNombre, ctc.numero as identificador, ctc.activo as Activo, x.perApellidoyNombre as Profesional, x.perId  as ProfesionalID " +
                           " from catTurneroConsultorio ctc " +
                           " inner join catTurnero ct on ct.csId = ctc.id_catTurnero " +
                           " left join  (select p.perId, p.perApellidoyNombre from catPersona p inner join catProfesion prof on prof.profId = p.profId union " +
                           " select c.conId, c.conApellidoyNombre from catPersonaContratados c inner join catProfesion prof on prof.profId = c.profId where conMotivoBaja is not null and conMotivoBaja is not null and c.conDNI not in (select perDNI from catPersona)) as x on x.perId = ctc.PerConId " +
                           " where ct.csId = @column and ctc.numero = @column2";
            }

            SqlDataAdapter da = new SqlDataAdapter(consulta, cx);
            da.SelectCommand.Parameters.AddWithValue("@column", csId);
            da.SelectCommand.Parameters.AddWithValue("@column2", identificador);

            DataTable dt = new DataTable();

            try
            {
                da.Fill(dt);
            }
            catch (Exception err)
            {
                return Json(err.Message);
            }
            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> row;
            foreach (DataRow dr in dt.Rows)
            {
                row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            return Json(rows);
        }
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GetProfesionalesJsonResult(string sistema, int? csId) {


            var result = "";


            SqlConnection cx = null;

            string consulta = "";

            if (sistema.ToLower() == "mho")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_MHO"].ConnectionString);
                consulta = "select p.ProfesionalID,  (p.Apellido + ', ' + p.Nombre) as Profesional from profesional p " +
                           " inner join ProfesionalEspecEmpr pe on p.ProfesionalID = pe.ProfesionalID and pe.EmpresaID = "+ csId +
                           " group by p.ProfesionalID, p.Apellido, p.Nombre order by p.Apellido, p.Nombre asc";
            }
            else if (sistema.ToLower() == "gedoc")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_GEDOC"].ConnectionString);
                consulta = "select p.perId as ProfesionalID, p.perApellidoyNombre as Profesional  " +
                            " from catAgenda ag inner " +
                            " join catPersona p on ag.perId = p.perId " +
                            " where ag.csId = @column and not exists(select x.* from catPersonaContratados x where x.conDNI = p.perDNI ) " +
                            " group by p.perId,p.perApellidoyNombre union " +
                            " select c.conId as ProfesionalID, c.conApellidoyNombre as Profesional " +
                            " from catAgenda ag inner " +
                            " join catPersonaContratados c on ag.perId = c.conId " +
                            " where ag.csId = @column and c.conFechaBaja is not null or c.conMotivoBaja is not null " +
                            " group by c.conId,c.conApellidoyNombre ";
            }
            SqlDataAdapter da = new SqlDataAdapter(consulta, cx);
            da.SelectCommand.Parameters.AddWithValue("@column", csId);

            DataTable dt = new DataTable();

            try
            {
                da.Fill(dt);
            }
            catch (Exception err)
            {
                return Json(err.Message);
            }
            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> row;
            foreach (DataRow dr in dt.Rows)
            {
                row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            return Json(rows);

        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult SaveProfesionalesJsonResult(string sistema, int? csId, int EstadoConsultorio, string ConsultorioNombre, int ProfesionalID, int ConsultorioNumero)
        {

            if (!CheckProfesionalesJsonResult(sistema, csId, ConsultorioNumero,EstadoConsultorio))
            {
                return Json("REPEATEDID");
            }
            var result = "";
            SqlConnection cx = null;
            string consulta = "";

            if (sistema.ToLower() == "mho")
            {
                cx = new SqlConnection(ConfigurationManager.ConnectionStrings["DB_MHO"].ConnectionString);
                consulta = "insert into catTurneroConsultorio (id_catTurnero, consultorio, numero, activo, PerConId) values " +

MVC Turnero/Views/Config/index2.cshtml
@{
    ViewBag.Title = "Configuración por profesional";
}
<h3> Configuración de consultorios</h3>

<br /><br />


<label class="textlabel">Nombre de Consultorio: </label><label style="font-size:14px;" class="label label-default" id="ConsultorioNombre">No disponible</label>
<br />

<label class="textlabel">Profesional asignado:  </label> <select id="profSelector" data-live-search="true" class="selectpicker" data-style="btn-default"></select>
<br />
<button class="btn btn-success" id="btnGuardar">Guardar cambios</button>
<hr/>

@*datatable con consultorios*@









<script>

    var id = @ViewBag.idConsultorio;
    var profesionales;


    $("#btnGuardar").click(function () {
        $.ajax({
            type: "POST",
            data:
                {
                            sistema: "@ViewContext.RouteData.Values["sistema"]",
                            csId: @ViewContext.RouteData.Values["csId"],
                            ProfesionalID: $("#profSelector").val(),
                            id: id
                },

            url: "@Url.Action("EditProfesionalesJsonResultId", "Config")",
            success: function(data)
            {
                console.dir(data);
                if(data =="true")
                {
                    alert("Modificado correctamente.");
                }
            },
            error: function(e)
            {
                event.stopPropagation();
                alert("error al acceder al servidor");
            }

        });

    });


    $(document).ready(function(){
        //carga una sola vez todos los profesionales
        $.post("@Url.Action("GetProfesionalesJsonResult", "Config")", {sistema: "@ViewContext.RouteData.Values["sistema"]",csId: @ViewContext.RouteData.Values["csId"]})
            .done(function(result) {
                profesionales = result;
                cargarCombo();
            });




            if(id==""){
                $("#ConsultorioNombre").text("Ingrese la url correctamente");
                $("#profSelector").remove();
                $("#btnGuardar").remove();
                $(".textlabel").remove();
            }else{
                TraerDatos(id);
            }



    });



    function TraerDatos(id)
    {

        $.ajax({
            type: "POST",
            data:
                {
                sistema: "@ViewContext.RouteData.Values["sistema"]",
                csId: @ViewContext.RouteData.Values["csId"],
                identificador: (id == "") ? "" : id
                },
            url: "@Url.Action("GetConfigConsultorioJsonResultId", "Config")",
            success: function(data)
            {
                console.dir(data);
                $("#ConsultorioNombre").text(data[0].ConsultorioNombre);
                $("#profSelector").selectpicker('val', data[0].ProfesionalID);
            },
            error: function(e)
            {
                event.stopPropagation();
                alert("error al acceder al servidor");
            }

        });
    }

    function cargarCombo() {


            for (var index in profesionales) {

                $("#profSelector")
                    .append("<option value=" +
                        profesionales[index].ProfesionalID +
                        "> " +
                        profesionales[index].Profesional +
                        " </option>");
            }
        $('#profSelector').selectpicker('refresh');

    }
</script>